<%

  def boxen?; ENV['BOXEN_HOME']; end
  url = ENV["BOXEN_POSTGRESQL_URL"]
  port = ENV["BOXEN_POSTGRESQL_PORT"]

  prod_user = ENV["RAILS_DB_USER"]
  prod_pass = ENV["RAILS_DB_PASS"]
  prod_db = ENV["RAILS_DB_NAME"]

%>

common: &common
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 50
  port: <%= port %>

production:
  <<: *common
  user: <%= prod_user %>
  database: <%= prod_db %>
  password: <%= prod_pass %>

development:
  <<: *common
  database: yourapp_development

test:
  <<: *common
  database: yourapp_test
